wellcome:
    path: /
    controller: App\Controller\WellcomeController::wellcome
newPost:
    path: /admin/post/new
    controller: App\Controller\PostController:newPost
listPost:
    path: /admin/post/list
    controller: App\Controller\PostController:listPost
viewPost:
    path: /admin/post/{slug}
    controller: App\Controller\PostController:viewPost
editPost:
    path: /admin/editPost/{slug}
    controller: App\Controller\PostController:editPost